# Generated by Django 4.2.7 on 2023-12-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('PLAYER', 'PLAYER'), ('COACH', 'COACH')], default=None, null=True),
        ),
    ]
