# Generated by Django 4.2.7 on 2023-12-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_player_alter_customuser_type_of_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='player',
        ),
    ]
