# Generated by Django 4.2.7 on 2023-12-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('position', models.CharField(choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('FORWARD', 'Forward')])),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField()),
                ('phone_number', models.CharField(max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
            ],
        ),
    ]
