# Generated by Django 4.2.7 on 2023-12-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('position', models.CharField(choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('FORWARD', 'Forward')])),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField()),
                ('phone_number', models.CharField(max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField()),
                ('training_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='SCHEDULED')),
                ('attendees', models.ManyToManyField(blank=True, to='main.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField()),
                ('host_score', models.IntegerField(blank=True, default=None, null=True)),
                ('guest_score', models.IntegerField(blank=True, default=None, null=True)),
                ('match_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='SCHEDULED')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='main.team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_match', to='main.team')),
            ],
        ),
    ]
