# Generated by Django 4.2.7 on 2023-12-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField()),
                ('host_score', models.IntegerField(blank=True, default=None, null=True)),
                ('guest_score', models.IntegerField(blank=True, default=None, null=True)),
                ('match_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='SCHEDULED')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='team.team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_match', to='team.team')),
            ],
        ),
    ]
